import os
import sys
import pandas as pd
from supabase import create_client, Client

# --- Config ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Read directly from the Gold inference/demo package generated by the models pipeline
GOLD_DATA_PATH = os.path.join(BASE_DIR, '..', 'demo_package_target_stop_run_90s.csv')

# Load .env locally if present
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

def export_to_supabase():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("❌ Error: SUPABASE_URL and SUPABASE_KEY must be set in .env or environment.")
        sys.exit(1)
        
    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    
    print(f"📦 Loading Gold inference results from: {GOLD_DATA_PATH}")
    if not os.path.exists(GOLD_DATA_PATH):
        raise FileNotFoundError(f"Missing Gold data file: {GOLD_DATA_PATH}")
        
    df = pd.read_csv(GOLD_DATA_PATH)
    
    # Map columns to Supabase Gold Schema
    df['game_id'] = df['gameId'].astype(str) if 'gameId' in df.columns else '22401052'
    df['period'] = df['period'].astype(int) if 'period' in df.columns else 1
    df['seconds_remaining'] = df['seconds_remaining'].astype(int) if 'seconds_remaining' in df.columns else 0
    df['score_margin'] = df['score_margin'].astype(int) if 'score_margin' in df.columns else 0
    df['predicted_stop_run_90s'] = df['cate'] if 'cate' in df.columns else df.get('target_stop_run_90s', 0.5)
    df['recommendation'] = df['predicted_stop_run_90s'].apply(lambda x: 'CALL_TIMEOUT' if x > 0.05 else 'HOLD')
    
    gold_cols = ['game_id', 'period', 'seconds_remaining', 'score_margin', 'predicted_stop_run_90s', 'recommendation']
    export_df = df[gold_cols].head(50).copy()
    
    records = export_df.to_dict(orient='records')
    
    print(f"🚀 Uploading {len(records)} Gold prediction records to Supabase 'nba_predictions'...")
    client.table('nba_predictions').insert(records).execute()
    print("✅ Gold export successful!")

if __name__ == "__main__":
    export_to_supabase()


